# Generated by Django 3.0 on 2020-05-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberian',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
