# Generated by Django 3.0 on 2020-05-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200524_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
