# Generated by Django 3.0 on 2020-05-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_allotment',
            name='email',
            field=models.CharField(default='Nil', max_length=100),
            preserve_default=False,
        ),
    ]
