# Generated by Django 3.0 on 2020-05-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_book_allotment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_allotment',
            name='issue_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_allotment',
            name='return_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
