# Generated by Django 3.0 on 2020-05-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_author_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='book_borrowed',
        ),
    ]
